### PR TITLE
Adds a mode to show all inputs and makes the view options toggles. Closes 573.

### PR DESCRIPTION
**Pull request by mmcdermott**
Also fixes a bug about `tbody` in scientific view.

### CODE REVIEW

**Comment by OAGr** [comment]
This seems weird to me, where is the background? 

image

Seems like it's in 'display mode'

**Comment by mmcdermott** [comment]
Corrected and re-staged at stage-matthew.getguesstimate.com

**Comment by mmcdermott** [comment]
Known issue: Height sticks after engaging scientific view.

**Comment by OAGr** [comment]
- [ ] Grid lines in background don't show.
- [ ] Highlight around selected arrows option doesn't show.
- [ ] /embed shows grid lines, but should not show them.
- [ ] You may want to add another option for 'gridlines' to hide or show those.

**Comment by OAGr** [comment]
This is on hold for me to make the correct icon.

**Pull request closed without merging**
