### PR TITLE
Set the metric readable id based on the metric name. Closes 748.

### PR DESCRIPTION
**Pull request by mmcdermott**

### CODE REVIEW

**Comment by OAGr** [comment]
image

Also, everything should be capitalized.

**Comment by OAGr** [comment]
Better, though right now this also abridges 'Population of Norway' to 'POP'.  It seems like 'PON' would be more intuitive.  We could make that another story; sorry for noticing it at the end.  Could also discuss more in person.

**Comment by mmcdermott** [comment]
Fixed. There was an existing error in the name to variable name function for facts that was preventing multi-word names being resolved to an acronym rather than an abbreviation, likely a holdout from our double-switching of directions on this section.

**Comment by OAGr** [comment]
This closes https://github.com/getguesstimate/guesstimate-app/issues/748

**Pull request merged**
